namespace OpenReplay
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }

    [default_interface]
    runtimeclass ClipLibraryWindow : Microsoft.UI.Xaml.Window
    {
        ClipLibraryWindow();
    }
}
